import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";

const inter_regular = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Live Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={`${inter_regular.className}}`}>
        {children}
      </body>
    </html>
  );
}
