import {Open_Sans } from "next/font/google";
import { ConfigProvider } from "antd";
import "./globals.css";

const inter_regular = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Live Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter_regular.className}}`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#C90739",
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
